[package]
name = "strong-units"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
type-level-logic = "0.1.0"

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
rand = "0.8"